### ISSUE TITLE
Context.startForegroundService() did not then call Service.startForeground(): com.google.android.play.core.assetpacks.AssetPackExtractionService}   

### ISSUE THREAD

**Issue by CellFari** [google/play-unity-plugins#119]
I am Using PAD in my game, and implemented according to documentation., But My ANR's percentage increase massively. here is log
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{92113c u0 com.google.android.play.core.assetpacks.AssetPackExtractionService} 
By Android version 

Android 10 (SDK 29) 

Android 9 (SDK 28) 

Type 

"main" prio=5 tid=1 Native 

Show lessexpand_less 

  #00  pc 0000000000096bdc  /apex/com.android.runtime/lib/bionic/libc.so (__epoll_pwait+20) 

  #00  pc 0000000000068655  /apex/com.android.runtime/lib/bionic/libc.so (epoll_wait+16) 

  #00  pc 00000000000106b5  /system/lib/libutils.so (android::Looper::pollInner(int)+120) 

  #00  pc 00000000000105c3  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+30) 

  #00  pc 00000000000d37e7  /system/lib/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long long, int)+24) 

  at android.os.MessageQueue.nativePollOnce (Native method) 

  at android.os.MessageQueue.next (MessageQueue.java:336) 

  at android.os.Looper.loop (Looper.java:178) 

  at android.app.ActivityThread.main (ActivityThread.java:7520) 

  at java.lang.reflect.Method.invoke (Native method) 

  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539) 

  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950) 

content_copy 

Type 

"ReferenceQueueDaemon" daemon prio=5 tid=7 Waiting 

Show moreexpand_more 

Type 

"Jit thread pool worker thread 0" daemon prio=5 tid=9 Native 

Show moreexpand_more 

Type 

"FinalizerWatchdogDaemon" daemon prio=5 tid=10 Waiting 

Show moreexpand_more 

Type 

"FinalizerDaemon" daemon prio=5 tid=11 Waiting 

Show moreexpand_more 

Type 

"Binder:29800_1" prio=5 tid=12 Native 

Show moreexpand_more 

Type 

"Binder:29800_2" prio=5 tid=13 Native 

Show moreexpand_more 

Type 

"Binder:29800_3" prio=5 tid=14 Native 

Show moreexpand_more 

Type 

"Profile Saver" daemon prio=5 tid=15 Native 

Show moreexpand_more 

Type 

"ScionFrontendApi" prio=5 tid=16 TimedWaiting 

Show moreexpand_more 

Type 

"pool-5-thread-1" prio=5 tid=17 Waiting 

Show moreexpand_more 

Type 

"Firebase-Messaging-Init" prio=5 tid=18 Waiting 

Show moreexpand_more 

Type 

"Firebase-Messaging-Topics-Io" prio=5 tid=20 Waiting 

Show moreexpand_more 

Type 

"Okio Watchdog" daemon prio=5 tid=22 Waiting 

Show moreexpand_more 

Type 

"pool-13-thread-1" prio=5 tid=23 Waiting 

Show moreexpand_more 

Type 

"FirebaseInstanceId" prio=5 tid=28 Waiting 

Show moreexpand_more 

Type 

"TcmReceiver" prio=5 tid=31 Native 

Show moreexpand_more 

Type 

"pool-13-thread-2" prio=5 tid=32 Waiting 

Show moreexpand_more 

Type 

"pool-13-thread-3" prio=5 tid=33 Waiting 

Show moreexpand_more 

Type 

"queued-work-looper" prio=5 tid=34 Native 

Show moreexpand_more 

Type 

"pool-13-thread-4" prio=5 tid=35 Waiting 

Show moreexpand_more 

Type 

"UnityMain" prio=5 tid=36 Native 

Show moreexpand_more 

Type 

"OkHttp ConnectionPool" daemon prio=5 tid=37 TimedWaiting 

Show moreexpand_more 

Type 

"AudioPortEventHandler" prio=5 tid=39 Native 

Show moreexpand_more 

Type 

"AudioTrack" prio=10 tid=40 Native 

Show moreexpand_more 

Type 

"Signal Catcher" daemon prio=5 tid=6 Runnable 

Show moreexpand_more 

Type 

"HeapTaskDaemon" daemon prio=5 tid=8 WaitingForTaskProcessor

**Comment by CellFari** [comment]
@jamcohen , can you look at this. Please help me out,
I need to fix it.. it severely impacts my game on store.

**Comment by jamcohen** [comment]
I've confirmed that this is an issue in the underlying Play Core library, but we haven't prioritized a fix because, in our experience, the ANR's are rare.
Do you have numbers on how many users are experiencing the crash?

**Comment by CellFari** [comment]
Yes I am sharing with you, Crash rate and ANR report, both have this ANR issue please its above threshold. Screen Shot
![image_2021_06_28T04_49_44_289Z](https://user-images.githubusercontent.com/45685937/123587583-ec898580-d7ff-11eb-8350-52742e7b1d25.png)

**Comment by CellFari** [comment]
Yes I am sharing with you, Crash rate and ANR report, both have this ANR issue please its above threshold. 
Please See 
![stab](https://user-images.githubusercontent.com/45685937/123587686-117df880-d800-11eb-8799-2027ffe45f71.png)
Screen Shot

**Comment by w121217** [comment]
I have the same problem,after clearing the cache,players need to download assetpacks,must be crash.  
Unity version = 2018.4.10f1 
PAD version = 1.4.0
Device Galaxy Tab A
Android 10

**Comment by CellFari** [comment]
@jamcohen , any update ? I have sent you screen shot of bad behavior..

**Comment by w121217** [comment]
hello,I can't see the screenshot you sent,can you sent to this mailbox?&nbsp; ***@***.***
thank you, thank you!&nbsp;&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "google/play-unity-plugins"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月29日(星期二) 下午3:26
***@***.***&gt;;
抄送:&nbsp;"Heart ***@***.******@***.***&gt;;
主题:&nbsp;Re: [google/play-unity-plugins] Context.startForegroundService() did not then call Service.startForeground(): com.google.android.play.core.assetpacks.AssetPackExtractionService}    (#119)





 
@jamcohen , any update ? I have sent you screen shot of bad behavior..

**Comment by jamcohen** [comment]
@CellFari, I've passed along the ANR report to the Play Core team.
I'll share more information as they get back to me.

**Comment by CellFari** [comment]
> @CellFari, I've passed along the ANR report to the Play Core team.
> I'll share more information as they get back to me.

Thank you so much, I am waiting for some positive answer from the team :)

**Comment by jamcohen** [comment]
@CellFari, do you mind sharing your app's package name, either here or with play-unity-plugin-support@googlegroups.com?

**Comment by CellFari** [comment]
> @CellFari, do you mind sharing your app's package name, either here or with [play-unity-plugin-support@googlegroups.com](mailto:play-unity-plugin-support@googlegroups.com)?

Yeah no problem, I shared my app's package id with you at  play-unity-plugin-support@googlegroups.com, and also share some more info about ANR, and my implementation.
please check and acknowledge me,
Thanks

**Comment by CellFari** [comment]
@jamcohen , hi there? any update?

**Comment by andryint** [comment]
The same problem here with severe impact on ANR rate in Android vitals.  Do you have some time estimates for the fix or recommendations for work around?

**Comment by jamcohen** [comment]
Hi @andryint,

Could you send your package name to play-unity-plugin-support@googlegroups.com?
I don't have a timeline for the fix or a workaround yet, but the Play Core team is investigating.

**Comment by andryint** [comment]
Hi, @jamcohen 

> Could you send your package name to play-unity-plugin-support@googlegroups.com?`

Sure. I just shared the bundle id  with  play-unity-plugin-support@googlegroups.com.
Please make me know in case some additional information  (e.g. implementation?) could help.

Thanks & regards

**Comment by CellFari** [comment]
@jamcohen , hi there any update on this?

**Comment by jamcohen** [comment]
Hi @CellFari,

Apologies for the late response.
I wish I had better news, but the Play Core team investigated and found that the ANR's aren't a significant enough problem to prioritize a fix. Because the issue is so hard to reproduce, we can't reliably test a fix without rolling it out to production apps. That makes attempting fixes time consuming and risky.

I'll update this bug if the situation changes.

**Comment by w121217** [comment]
I have methods to reproduce,
First download some assetpackage form GooglePlay.
And clearing the cache.
And download the assetpackage form GooglePlay once again.
Wait 15 seconds.
Must be crash.
My English is not good, do i have to clarify?

**Comment by jamcohen** [comment]
@w121217, are you saying those steps cause this ANR?
`Context.startForegroundService() did not then call Service.startForeground()`

That would be great news. I'll try this later today.

**Comment by jamcohen** [comment]
@w121217, which cache did you clear? The app's cache or the Play Store's cache?

**Comment by w121217** [comment]
@jamcohen the app's cache

**Comment by CellFari** [comment]
> @w121217, which cache did you clear? The app's cache or the Play Store's cache?

@jamcohen did you try this? any update

**Comment by jamcohen** [comment]
I did, and it didn't trigger the ANR for me.
@CellFari, is this something you could try in your app?

**Comment by CellFari** [comment]
> I did, and it didn't trigger the ANR for me.
> @CellFari, is this something you could try in your app?

Sure Let me give a try,

**Comment by liqibo-code** [comment]
Caused by android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{119e102 u0 com.digitalkingdom.cookinghome/com.google.android.play.core.assetpacks.AssetPackExtractionService}
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1872)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7045)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

This bug still exists in the v1.6.0 version！
@jamcohen

**Comment by liqibo-code** [comment]
Caused by android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{119e102 u0 com.xxxx.yyyygame/com.google.android.play.core.assetpacks.AssetPackExtractionService}
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1872)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7045)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

This bug still exists in the v1.6.0 version！
@jamcohen

**Comment by CodeForCSharp** [comment]
> Hi @CellFari,
> 
> Apologies for the late response. I wish I had better news, but the Play Core team investigated and found that the ANR's aren't a significant enough problem to prioritize a fix. Because the issue is so hard to reproduce, we can't reliably test a fix without rolling it out to production apps. That makes attempting fixes time consuming and risky.
> 
> I'll update this bug if the situation changes.

This problem is easy to reproduce,use an old version play store,like 23.0.x.
The new version play store can't reproduce,like 29.4.x.
This problem still exists in play-core lib 1.10.2.
Any solution for this problem?

**Comment by jamcohen** [comment]
The Play Core team has removed all references to Context.startForegroundService() in play-core lib 1.10.3 which is the version used in the latest 1.7.0 release. Updating the play core library should fix the issue.

**Comment by PrabhatK-Bsw** [comment]
@jamcohen Hi, we are using the 1.7.0 but still getting following issue:
Caused by android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{833be9 u0 com.companyname.appname/com.google.android.play.core.assetpacks.AssetPackExtractionService}
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1874)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

Using following Packages versions:
 "com.google.android.appbundle": "file:../GooglePackages/com.google.android.appbundle-1.7.0.tgz",
    "com.google.external-dependency-manager": "file:../GooglePackages/com.google.external-dependency-manager-1.2.172.tgz",
    "com.google.play.assetdelivery": "file:../GooglePackages/com.google.play.assetdelivery-1.7.0.tgz",
    "com.google.play.common": "file:../GooglePackages/com.google.play.common-1.7.0.tgz",
    "com.google.play.core": "file:../GooglePackages/com.google.play.core-1.7.0.tgz",
    "com.google.play.review": "file:../GooglePackages/com.google.play.review-1.7.0.tgz",

**Comment by liqibo-code** [comment]
This bug still exists in the v1.8.0 version！

**Comment by liqibo-code** [comment]
Android 9

----------------------------------------------------------------------------------------------------------------

Fatal Exception: java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2019.4.30f1c1
Device model      : samsung SM-G9500
Device fingerprint: samsung/dreamqltezc/dreamqltechn:9/PPR1.180610.011/G9500ZCU3DSD1:user/release-keys

----------------------------------------------------------------------------------------------------------------

Caused by android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{8e3d7b6 u0 com.sevenminutesjoy.mergefrenzy/com.google.android.play.core.assetpacks.AssetPackExtractionService}
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1872)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7045)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by yangjiayuGIT** [comment]
![image](https://user-images.githubusercontent.com/29367940/196608646-f67cf768-0181-4133-a314-dacda8ca67b5.png)
Unity version : 2019.4.29f1
Device model : vivo-V2171A
Android 12,level 31
implementation 'com.google.android.play:asset-delivery:2.0.0'
implementation 'com.google.android.play:core-common:2.0.1'
